### PR TITLE
Replace deprecated force_text with force_str

### PR DESCRIPTION
**Pull request by dfrank-a**

### CODE REVIEW

**Comment by jckw** [comment]
Hey @dfrank-a ! Thanks for the PR. Any more info on why it's needed?

**Comment by cerih** [comment]
Hi @jckw 

Any chance this will be merged soon to support Django 4.x?

Also `force_str` has existing since at least Django 1.8 so this will have likely have no impact for those users not pinning the package version - see https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.encoding.force_str

**Comment by mwx23** [comment]
This issue is also affecting a Django 4.x project I am working on.

**Comment by jckw** [comment]
New version includes this change: https://pypi.org/project/django-bootstrap-daterangepicker/1.1.0/

**Comment by cerih** [comment]
Much appreciated!  Thanks for your package - we make good use of it.

**Pull request merged**
