### PR TITLE
Catches import error of six in Django 3

### PR DESCRIPTION
**Pull request by farridav**
This package no longer works with Django 3, Im hoping with this fix, it will

Django removed vendored six library, in favor of official one https://bit.ly/2WYMdyW

### CODE REVIEW

**Comment by farridav** [comment]
@jckw any chance of a review/release ? its a tiny compatability change and will help out everyone upgrading to Django 3.0 . Thanks

**Comment by jckw** [comment]
Can we just add `six` to requirements and remove the if condition? Is there a reason that doesn't work?

**Comment by farridav** [comment]
The reason I didn't is that Six is now a sub-dependency of Django, and if we add it as a sub dependency of here then we might be competing for pinning the version.

Also doing it this way preserves full backwards compatibility for those using the version of the six library from Django.

**Comment by farridav** [comment]
On the flip side, "explicit is better than implicit", let me know how you want to proceed :)

**Comment by jckw** [comment]
Let's add six to the requirements and just use the external package. Also a version bump would be good!

**Comment by farridav** [comment]
Cool, done :)

**Comment by jckw** [comment]
Could you also bump the version to 1.0.6? Can do a release straight after that https://github.com/jckw/django-bootstrap-daterangepicker/blob/master/setup.py#L10

**Comment by jckw** [comment]
In fact, don't worry. I can do that

**Pull request merged**
